CONFIG = {
    'ANTARANEWS': {
        'NAME': 'Antara News',
        'START': 'https://www.antaranews.com/indeks/%s',
        'ARTICLES': '//article[@class="simple-post simple-big clearfix"]/header/h3/a/@href',
        'NEXT_PAGES': '//ul[@class="pagination pagination-sm"]/li/a[@aria-label="Next"]/@href',
        'TITLE': '//h1[@class="post-title"]/text()',
        'AUTHOR': '//p[@class="text-muted small mt10"]//text()[2]',
        'DATE': '//meta[@property="article:published_time"]/@content',
        'DATE_FORMAT': '%Y-%m-%dT%H:%M:%S+07:00',
        'TAG': '//ul[@class="tags-widget clearfix"]/li/a/text()',
        'CATEGORY': '//p[@class="simple-share"]/a/@title',
        'CONTENTS': '//div[@class="post-content clearfix"]//text()',
        'EXCLUDE_LINK': '//b//text()',
        'ART_DATE': '//article[@class="simple-post simple-big clearfix"]/header/p/span/text()'
    },
    'BERITAJAKARTA': {
        'NAME': 'Berita Jakarta',
        'START': 'http://www.beritajakarta.id/news_index',
        'ARTICLES': '//div[@class="col-md-9"]/h4/a/@href',
        'NEXT_PAGES': '//ul[@class="pagination"]/li/a/@href',
        'TITLE': '/',
        'AUTHOR': '/',
        'DATE': '/',
        'DATE_FORMAT': '%Y-%m-%dT%H:%M:%S+07:00',
        'TAG': '/',
        'CATEGORY': '//ol[@class="breadcrumb"]/li[2]/a/text()',
        'CONTENTS': '//div[@class="clearfix mt-10"]/p/text() | //div[@align="left"]/p/text()',
    },
    'BERITASATU': {
        'NAME': 'Berita Satu',
        'START': 'http://www.beritasatu.com/newsindex?indate=%s',
        'ARTICLES': '//div[@class="media custom-media-index"]/div[@class="media-body"]/a/@href',
        'NEXT_PAGES': '//ul[@class="pagination modal-1"]/li/a/@href',
        'TITLE': '//div[@class="title_post landing-headline frr"]/h1/text()',
        'AUTHOR': '//span[@class="hz_post_by"]/text()',
        'DATE': '//span[@class="hz_date_post"]/text()',
        'DATE_FORMAT': '%A, %d %B %Y | %H:%M WIB',
        'TAG': '/',
        'CATEGORY': '/',
        'CONTENTS': '//div[@class="hz_content mr"]//text()',
        'STOP_CRITERION': r'Sumber: '
    },
    'BISNIS': {
        'NAME': 'Bisnis',
        'START': 'https://www.bisnis.com/index?categoryId=0&type=indeks&date=%s',
        'ARTICLES': '//div[@id="indeksListView"]//a[@class="artLink artLinkImg"]/@href',
        # 'NEXT_PAGES': '//a[contains(@aria-label, "Next")]/@href',
        'NEXT_PAGES': '//ul[@class="pages page-indeks"]/li/a/@href',
        'TITLE': '//div[contains(@class, "col-custom") or contains(@class, "detail")]/h1/text()',
        'AUTHOR': '//div[@class="detailsAuthorItem"]/a/text()',
        'DATE': '//meta[@property="article:published_time"]/@content',
        'DATE_FORMAT': '%Y-%m-%dT%H:%M:%S+07:00',
        'TAG': '//ul[@class="detailsTagList display-flex"]//text()',
        'CATEGORY': '//ul[@class="breadcrumbList"]/li[3]/a/text()',
        'CONTENTS': '//article[contains(@class, "detailsContent")]//text()'
    },
    'CNN': {
        'NAME': 'CNN',
        # 'START': 'https://www.cnnindonesia.com/indeks/3?date=%s',
        'START': 'https://www.cnnindonesia.com/indeks?date=%s',
        'ARTICLES': '//article[@class="flex-grow"]/a/@href',
        'NEXT_PAGES': '//article[@class="flex gap-5 my-8 items-center justify-center undefined"]/a[last()]/@href',
        # 'NEXT_PAGES': '/',
        'TITLE': '//title/text()',
        # 'TITLE': '//meta[@name="originalTitle"]/@content',
        'AUTHOR': '//meta[@name="author"]/@content',
        # 'DATE': '//meta[@name="publishdate"]/@content',
        # 'DATE_FORMAT': '%Y-%m-%d %H:%M:%S',
        'DATE': '//meta[@name="dtk:publishdateunix"]/@content',
        'DATE_FORMAT': '%Y-%m-%d %H:%M:%S',
        'TAG': '//meta[@name="tag"]/@content',
        # 'TAG': '//div[@class="detail_tag mb20"]/a/text()',
        # 'CATEGORY': '//a[@class="gtm_breadcrumb_kanal"]//text()',
        'CATEGORY': '//meta[@name="dtk:namakanal"]/@content',
        # 'CONTENTS': '//div[@id="detikdetailtext"]/p//text()',
        'CONTENTS': '//div[@class="detail-text text-cnn_black text-sm grow min-w-0"]//p//text()',
    },
    'DETIK': {
        'NAME': 'Detik',
        'START': 'https://news.detik.com/indeks/?date=%s',
        'ARTICLES': '//article//h3[@class="media__title"]/a/@href',
        'NEXT_PAGES': '//div[@class="pagination text-center mgt-16 mgb-16"]/a[last()]/@href',
        'TITLE': '//title/text()',
        'AUTHOR': '//meta[@name="author"]/@content',
        'DATE': '//meta[@name="publishdate"]/@content',
        'DATE_FORMAT': '%Y/%m/%d %H:%M:%S',
        'TAG': '//meta[@name="keywords"]/@content',
        'CATEGORY': '//div[@class="page__breadcrumb"]/a[2]/text()',
        # 'CONTENTS': '//div[contains(@class,"itp_bodycontent")]/p//text()',
        'CONTENTS': '//div[@class="detail__body-text itp_bodycontent"]//text()',
        'EXCLUDE_LINK': '// table[@class = "linksisip"]//text() | //style//text() | //script//text() | //div[@class="aevp"]//text()',
        'EXCLUDE_TEXT': r'Tonton juga|Tonton video|detik]|\r\nADVERTISEMENT\r\n|\r\nSCROLL TO CONTINUE WITH CONTENT\r\n|Simak juga.*|Simak selengkapnya.*|Baca selengkapnya.*|\[Gamba.*|Simak Video*',
        'STOP_CRITERION': r'\(\S+\/\S+\)'
    },
    'INILAH': {
        'NAME': 'Inilah',
        'START': 'https://www.inilah.com/indeks/',
        'ARTICLES': '//div[@class="w-li"]//a/@href',
        'NEXT_PAGES': '/',
        'TITLE': '//h2[@id="current-title-0"]/text()',
        'AUTHOR': '//h6/span/text()',
        'DATE': '/',
        'DATE_FORMAT': ' %A, %d %B %Y ',
        'TAG': '//ul/li/h2/a/text()',
        'CATEGORY': '/',
        'CONTENTS': '//div[@class="article-content"]/p/text()',
        'FORM_DATA': {
            'kanal': '0',
            'submit': 'cari'
        },
    },
    'JAKARTAPOST': {
        'NAME': 'Jakarta Post',
        'START': 'https://www.thejakartapost.com/news/index',
        'ARTICLES': '//div[@class="newsWord"]/a[2]/@href',
        'NEXT_PAGES': '//div[@class="navigation-page"]/a/@href',
        'TITLE': '//h1[@class="title-large"]/text()',
        'AUTHOR': '//span[@class="name-post"]/text()',
        'DATE': '//span[@class="day"]/text()',
        'DATE_FORMAT': '%a, %B %d, %Y',
        'TAG': '//div[@class="topicRelated"]/ul/li/a/text()',
        'CATEGORY': '//a[@class="dt-news"]/text()',
        'CONTENTS': '//div[@class="col-md-10 col-xs-12 detailNews"]//text()',
        'STOP_CRITERION': r'Topics :',
    },
    'KOMPAS': {
        'NAME': 'Kompas',
        #'START': 'https://indeks.kompas.com/news/%s',
        'START': 'https://news.kompas.com/search/%s',
        'ARTICLES': '//a[@class="article__link"]/@href',
        'NEXT_PAGES': '//div[@class="paging__wrap clearfix"]/div[@class="paging__item"]//a[text()="Next"]/@href',
        'TITLE': '//title/text()',
        # 'AUTHOR': '//meta[@name="author"]/@content',
        'AUTHOR': '//meta[@name="content_author"]/@content',
        'DATE': '//meta[@name="content_PublishedDate"]/@content',
        'DATE_FORMAT': '%Y-%m-%d %H:%M:%S',
        # 'TAG': '//meta[@name="content_subcategory"]/@content',
        'TAG': '//meta[@name="keywords"]/@content',
        # 'CATEGORY': '//meta[@name="content_tags"]/@content',
        'CATEGORY': '//meta[@name="content_subcategory"]/@content',
        'CONTENTS': '//div[@class="read__content"]//p//text()',
        'EXCLUDE_TEXT': r'Baca Juga:',
    },
    'KONTAN': {
        'NAME': 'Kontan',
        'START': 'https://www.kontan.co.id/search/indeks?kanal=&tanggal=%s&bulan=%s&tahun=%s&pos=indeks',
        'ARTICLES': '//div[@class="list-berita"]//li/a/@href',
        'NEXT_PAGES': '//ul[@class="cd-pagination"]/li[last()]/a/@href',
        # 'TITLE': '//title/text()',
        # 'TITLE': '//div[@class="bag-kiri"]/h1[@class="detail-desk"]/text()',
        'TITLE': '//meta[@property="og:title"]/@content',
        'AUTHOR': '//meta[@name="content_author"]/@content',
        'DATE': '//meta[@name="content_PublishedDate"]/@content',
        'DATE_FORMAT': '%Y-%m-%d %H:%M:%S',
        'TAG': '//meta[@name="content_tag"]/@content',
        'CATEGORY': '//meta[@name="content_category"]/@content',
        'CONTENTS': '//div[@class="tmpt-desk-kon" or @class="ctn"]/*[self::p|self::ol|self::ul]//text()[not(ancestor::strong)]'
    },
    'CNBC': {
        'NAME': 'CNBC',
        'START': 'https://www.cnbcindonesia.com/indeks?date=%s',
        # 'START': 'https://www.cnbcindonesia.com/indeks/3?date=%s',
        'ARTICLES': '//a[@class="group flex gap-4 items-center"]/@href',
        # 'NEXT_PAGES': '//div[@class="paging text_center gtm_paging"]/a[last()]/@href',
        'NEXT_PAGES': '//div[@class="flex gap-1 items-center justify-center m-0"]/a[last()]/@href',
        'TITLE': '//title/text()',
        'AUTHOR': '//meta[@name="author"]/@content',
        'DATE': '//meta[@name="publishdate"]/@content',
        'DATE_FORMAT': '%Y/%m/%d %H:%M:%S',
        'TAG': '//meta[@name="tag"]/@content',
        'CATEGORY': '//meta[@name="dtk:namakanal"]/@content',
        # 'CONTENTS': '//div[@class="detail_text"]/*[self::p|self::ol|self::ul]//text()[not(ancestor::strong) and not(ancestor::script)]'
        'CONTENTS': '//div[@class="detail-text"]//p//text()',
    },
    'LIPUTAN6': {
        'NAME': 'Liputan6',
        'START': 'https://www.liputan6.com/news/indeks/%s',
        'ARTICLES': '//h4[@class="articles--rows--item__title"]/a/@href',
        'NEXT_PAGES': '//div[@class="simple-pagination__container"]/a/@href',
        'TITLE': '//h1[@class="read-page--header--title entry-title"]//text()',
        'AUTHOR': '//span[@class="read-page--header--author__name fn"]/text()',
        'DATE': '//meta[@property="article:published_time"]/@content',
        'DATE_FORMAT': '%Y-%m-%dT%H:%M:%S+07:00',
        # 'TAG': '//ul[@class="tags--snippet__list"]/li/a/span/text()',
        'TAG': '//meta[@name="keywords"]/@content',
        'CATEGORY': '//li[@class="read-page--breadcrumb--item"][2]//text()',
        'CONTENTS': '//div[@class="article-content-body article-content-body_with-aside"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="baca-juga"]//text()',
        'EXCLUDE_TEXT': r'Baca Juga|Saksikan video pilihan di bawah ini:',
        'STOP_CRITERION': r'Sumber: .*',
    },
    'MEDIA INDONESIA': {
        'NAME': 'Media Indonesia',
        # 'START': 'http://mediaindonesia.com/read',
        'START': 'https://mediaindonesia.com/indeks',
        # 'ARTICLES': '//div[@class="article-content"]/h2/a/@href',
        'ARTICLES': '//div[@class="text "]/h3/a/@href',
        'NEXT_PAGES': '//div[@class="pagination"]/a/@href',
        # 'TITLE': '//div[@class="article-title"]/h1/b/text()',
        'TITLE': '//div[@class="post-header"]/h1/text()',
        # 'AUTHOR': '//div[@class="author"]/div[@class="a-content"]/span/b/text()',
        'AUTHOR': '//div[@class="info-author"]//a[@class="author"]/text()',
        # 'DATE': '//div[@class="article-title"]/div/div/span[@class="meta"]/text()',
        'DATE': '//div[@class="info"]/span[@class="datetime"]/text()',
        # 'DATE_FORMAT': '%A, %d %b %Y, %H:%M WIB',
        'DATE_FORMAT': '%d/%m/%Y %H:%M',
        # 'TAG': '//div[@class="article-tags tag-cloud"]/a/text()',
        'TAG': '//ul[@class="related-tags"]/li/a/text()',
        # 'CATEGORY': '/',
        'CATEGORY': '//ul[@class="mi-breadcrumb"]/li[2]/a/text()',
        # 'CONTENTS': '//div[@itemprop="articleBody"]//text()',
        'CONTENTS': '//div[@class="article"]//p//text()',
        'EXCLUDE_LINK': '//div[@itemprop="articleBody"]//a/text() | //div[@class="dable_placeholder"]//text() | //p[@class="related-news"]//text()',
        'EXCLUDE_TEXT': r'Baca juga:',
        # 'ART_DATE': '//div[@class="article-content"]/span/a[2]/text()',
        'ART_DATE': '//ul[@class="list-3"]/li/div[@class="text "]/span/text()'

    },
    'MERDEKA': {
        'NAME': 'Merdeka',
        'START': 'https://www.merdeka.com/indeks-berita/%s',
        'ARTICLES': '//ul[@class="mdk-idn-nd-centlist"]/li/a/@href',
        'NEXT_PAGES': '//div[@class="mdk-page"]/a/@href',
        'TITLE': '//div[@class="mdk-dt-headline"]/h1/text()',
        'AUTHOR': '//div[@class="col-dt-left"]/span[@class="reporter"]/a//text()',
        'DATE': '//span[@class="date-post"]/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M:%S',
        'TAG': '//ol[@class="mdk-list-terkait"]/li/a/text()',
        'CATEGORY': '//div[@class="mdk-breadcrumb"]/a[2]/text()',
        'CONTENTS': '//div[contains(@class,"mdk-body-paragraph")]/p/text()[not(ancestor::*[contains(@class, "dont-display")])]',
        'ART_DATE': '//span[@class="mdk-idn-date"]/text()',
        'EXCLUDE_TEXT': r'Reporter:.*|Reporter Magang:.*|Sumber:.*'
    },
    'METROTVNEWS': {
        'NAME': 'Metrotvnews',
        'START': 'http://www.metrotvnews.com/index/%s',
        'ARTICLES': '//ul/li/h2/a/@href',
        'NEXT_PAGES': '/',
        'TITLE': '//div[@class="detail"]/h1/text()',
        'AUTHOR': '//div[@class="reg"]/text()',
        'DATE': '//div[@class="reg"]/text()',
        'DATE_FORMAT': '%A, %d %b %Y %H:%M WIB',
        'TAG': '//div[@class="line"]/a/text()',
        'CATEGORY': '//div[@class="breadcrumbs"]/a[2]/text()',
        'CONTENTS': '//div[@class="page"]//text()',
        'EXCLUDE_LINK': '//div[@class="related"]//text() || //div[@class="page"]//script/text()',
        'EXCLUDE_TEXT': r'.*Video.*',
        'STOP_CRITERION': r'\(\S+\)'
    },
    'OKEZONE': {
        'NAME': 'Okezone',
        'START': 'https://index.okezone.com/bydate/index/%s',
        'ARTICLES': '//h4[@class="f17"]/a/@href',
        'NEXT_PAGES': '//div[@class="pagination-indexs"]//a[text()="Next>"]/@href',
        'TITLE': '//div[@class="title"]/h1/text()',
        'AUTHOR': '//meta[@property="dable:author"]/@content',
        'DATE': '//meta[@property="article:published_time"]/@content',
        'DATE_FORMAT': '%Y-%m-%dT%H:%M:%S+07:00',
        # 'TAG': '//meta[@name="news_keywords"]/@content',
        # 'TAG': '//meta[@name="keywords"]/@content',
        'TAG': '//meta[@name="meta_keywords"]/@content',
        'CATEGORY': '//meta[@property="article:section2"]/@content',
        'CONTENTS': '//div[@id="contentx"]//p//text()',
        'EXCLUDE_TEXT': r'.*baca juga.*',
        'LINK_NEXT_PAGE': '//div[@class="next"]/a[not(@title)]/@href'
    },
    'PIKIRAN-RAKYAT': {
        'NAME': 'Pikiran Rakyat',
        'START': 'https://www.pikiran-rakyat.com/indeks-berita',
        'ARTICLES': '//h2[@class="latest__title"]/a/@href', 
        'NEXT_PAGES': '//div[@class="paging__wrap clearfix"]/div/a[@class = "paging__link paging__link--prev"]/@href',
        'TITLE': '//div[@class="mt3 clearfix"]/h1/text()',
        'AUTHOR': '//meta[@name="author"]/@content',
        'DATE': '//date[@class="latest__date"]/text()',
        'ART_DATE': '//date[@class="latest__date"]/text()',
        'DATE_FORMAT' : '%d %B %Y, %H:%M WIB',
        'TAG': '//ul[@class="tag__list"]/li/h4/a/text()',
        'CATEGORY': '//div[@class="col-bs12-12"]//ul/li[2]/a/text()',
        'CONTENTS': '//article[@class="read__content clearfix"]/p/text() | //article[@class="read__content clearfix"]/p/a/text() | //article[@class="read__content clearfix"]/p/span/text() | //article[@class="read__content clearfix"]/p/span/a/text()',
    },
    'REPUBLIKA': {
        'NAME': 'Republika',
        'START': 'https://www.republika.co.id/index/%s/%s/%s/%s',
        'ARTICLES': '//li[@class="list-group-item list-border conten1"]/a/@href',
        'NEXT_PAGES': '//nav[@role="navigation"]/a[text()="Next"]/@href',
        'TITLE': '//meta[@name="twitter:title"]/@content',
        'AUTHOR': '//div[@class="max-card__title"]/div/a/text()',
        'DATE': '//meta[@property="article:published_time"]/@content',
        'DATE_FORMAT': '%Y-%m-%dT%H:%M:%S+0700',
        'TAG': '//meta[@name="keywords"]/@content',
        'CATEGORY': '//meta[@property="article:section2"]/@content',
        'CONTENTS': '//div[@class="artikel" or @class="teaser_detail" or @class="news-cover" or contains(@class,"read-news") or contains(@class, "article-read")]/p//text()|//article/p//text()',
        'CSRF_TOKEN': '//input[@name="csrf_token_1f575b49"]/@value',
        'EXCLUDE_LINK': '//div[@class="baca-juga"]//text()',
        'EXCLUDE_TEXT': r'Baca Juga|baca juga|Baca juga',
        'STOP_CRITERION': r'.*BACA JUGA.*',
        'FORM_DATA': {
            'kanal': '',
            'subkanal': '',
            'day': '1',
            'month': '1',
            'year': '1970',
            'offset': '0',
            'csrf_token_1f575b49': ''
        },
        'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36'
    },
    'SINDO': {
        'NAME': 'Sindo',
        'START': 'https://index.sindonews.com/index/0?t=%s',
        'ARTICLES': '//div[@class="indeks-title"]/a/@href',
        'NEXT_PAGES': '//div[@class="pagination"]/ul/li/a[@rel="next"]/@href',
        'LINK_NEXT_PAGE': '//li[@class="article-next"]//@href',
        'TITLE': '//meta[@property="og:title"]/@content',
        'AUTHOR': '//div[@class="detail-nama-redaksi"]/a/text()',
        'DATE': '//div[@class="detail-date-artikel"]/text()',
        'DATE_FORMAT': '%A, %d %B %Y - %H:%M WIB',
        'TAG': '//div[@class="topik"]/ul/li/a/text()',
        'CATEGORY': '//div[@class="left-section"]//ul/li[2]/a/text()',
        'CONTENTS': '//div[@class="detail-desc"]//text()[not(ancestor::*[contains(@class, "baca-inline")])]',
        'EXCLUDE_TEXT': r'.*baca juga:',
        'STOP_CRITERION': r'Berita Terkait|Lihat Juga:'
    },
    'SUARA': {
        'NAME': 'Suara',
        'START': 'https://www.suara.com/indeks/terkini/all/%s',
        'ARTICLES': '//div[@class="list-item-y-img-retangle"]//a/@href',
        'NEXT_PAGES': '//ul[@class="pagination"]/li/a/@href',
        'TITLE': '//meta[@property="og:title"]/@content',
        'AUTHOR': '//div[@class="writer"]/span//text()',
        'DATE': '//div[@class="date-article"]/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y | %H:%M WIB',
        'TAG': '//meta[@name="keywords"]/@content',
        'CATEGORY': '//div[@class="top-detail"]//a/text()',
        'ALT_CATEGORY': '//meta[@property="article:section2"]/@content',
        # 'CONTENTS': '//article[@class="detail-content detail-berita"]/p//text()',
        'CONTENTS': '//article[@class="detail-content detail-berita live-report2"]/p//text()',
        'EXCLUDE_TEXT': r'Baca Juga:'
    },
    'SUARAMERDEKA': {
        'NAME': 'Suara Merdeka',
        'START': 'https://www.suaramerdeka.com/index.php/news/indeks?d=%s',
        'ARTICLES': '//h3[@class="title-semibold-dark size-lg mb-15"]/a/@href',
        'NEXT_PAGES': '//ul[@class="pagination"]/li/a/@href',
        'TITLE': '//h2[@class="title-semibold-dark size-c30"]/text()',
        'AUTHOR': '/',
        'DATE': '//ul[@class="post-info-dark mb-30"]/li[1]/a/text()[2]',
        'DATE_FORMAT': '%a, %d %b %Y - %H:%M WIB',
        'TAG': '//ul[@class="blog-tags item-inline"]/li/a/text()',
        'CATEGORY': '//ul[@class="post-info-dark mt-10"]/li/a/text()[2]',
        'CONTENTS': '//div[@class="news-details-layout1"]/p/text()',
        'STOP_CRITERION': r'\(\S+\/\S+\/\S+\)'
    },
    'TEMPO': {
        'NAME': 'Tempo',
        'START': 'https://www.tempo.co/indeks/%s',
        # 'ARTICLES': '//article//a/@href',
        'ARTICLES': '//main[@class="main-left"]//h2[@class="title"]//a//@href',
        'NEXT_PAGES': '/',
        'TITLE': '//article[@class="detail-artikel"]//h1/text()',
        # 'AUTHOR': '//div[@class="box-avatar margin-right-sm"]//a/span/text()',
        'AUTHOR': '//meta[@name="author"]/@content',
        'DATE': '//p[@class="date margin-bottom-sm"]/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIB',
        'TAG': '//meta[@name="keywords"]/@content',
        'CATEGORY': '//meta[@name="adx:sections"]/@content',
        'CONTENTS': '//div[@class="detail-konten"]/p//text()',
        'EXCLUDE_LINK': '//div[@class="detail-in"]/p/strong/em/a/text()',
        'STOP_CRITERION': r'Pilihan Editor:|Baca juga|Baca.*:|Selalu update info terkini.'
    },
    'TRIBUN': {
        'NAME': 'Tribun',
        'START': 'https://www.tribunnews.com/index-news?date=%s',
        # 'START': 'https://www.tribunnewswiki.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        # 'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'NEXT_PAGES': '//div[@class="paging"]/a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        # 'AUTHOR': '//div[@class="sources mb20"]//a/@title',
        'AUTHOR': '//div[@class="f20 credit mt10"]//div[@id="penulis"]//text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIB',
        # 'TAG': '//h5[@class="tagcloud3"]//text()',
        'TAG': '//meta[@name="news_keywords"]/@content',
        # 'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CATEGORY': '//h2[@class="red f16"]//a/@title',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'VIVA': {
        'NAME': 'VIVA',
        'START': 'https://www.viva.co.id/request/load-more-indeks',
        'ARTICLES': '//a[@class="article-list-title"]/@href',
        'NEXT_PAGES': '/',
        'TITLE': '//title/text()',
        'AUTHOR': '//div[@class="main-content-author"]//a/text()',
        'DATE': '//meta[@property="article:published_time"]/@content',
        'DATE_FORMAT': '%Y-%m-%dT%H:%M:%S+07:00',
        'TAG': '//meta[@name="news_keywords"]/@content',
        'CATEGORY': '//meta[@property="article:section2"]/@content',
        'CONTENTS': '//div[@class="main-content-detail"]/p/text()',
        'ART_DATE': '//div[@class="article-list-date content_center"]/span/text()',
        'FORM_DATA': {
            'channel_name': 'all',
            'subchannel_name': 'all',
            'page': '1',
            'record_count': '12',
            '_token': 'yeY8TyUQJ6UivnuKyl7CsljgVoDYPi1ytFKw6F3P',
        },
    },
    'INEWS': {
        'NAME': 'INews',
        'START': 'https://www.inews.id/indeks/all/%s',
        'ARTICLES': '//div[@class="news-feed"]//a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//meta[@property="og:title"]/@content',
        'AUTHOR': '//div[@class="author"]/text()[2]',
        'DATE': '//time[@id="publishDate"]/@datetime',
        'DATE_FORMAT': '%Y-%m-%d %H:%M:%S',
        'TAG': '//meta[@name="keywords"]/@content',
        'CATEGORY': '//ul[@class="breadcrumb"]//a/text()',
        'CONTENTS': '//div[@itemprop="articleBody"]/p//text()'
    },
    'JPNN': {
        'NAME': 'Jpnn',
        'START': 'https://www.jpnn.com/indeks?id=&d=%s&m=%s&y=%s&tab=all',
        'ARTICLES': '//ul[@class="content-list"]//h1/a/@href',
        'NEXT_PAGES': '//div[@class="pagination"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@class="judul"]/text()',
        'AUTHOR': '//meta[@name="jpnncom_news_author"]/@content',
        'DATE': '//span[@class="date-publish"]/text()',
        'DATE_FORMAT': '%A, %d %B %Y - %H:%M WIB',
        'TAG': '//meta[@name="keywords"]/@content',
        'CATEGORY':'//div[@class="breadcrumb"]//a/text()',
        'CONTENTS': '//div[@itemprop="articleBody"]/p//text()'
    },
    'MEDCOM': {
        'NAME': 'Medcom',
        'START': 'https://www.medcom.id/index',
        'SUB_START' : '//div[@class="ti_1 white"]//a/@href',
        'ARTICLES': '//div[@class="box_21"]//h2/a/@href',
        'NEXT_PAGES': '//ul[@class="pagination"]//a[text()="Next"]/@href',
        'TITLE': '//h1/text()',
        'AUTHOR': '//div[@class="info_ct"]/text()',
        'DATE': '//div[@class="info_ct"]/text()',
        'DATE_FORMAT': '%d %B %Y %H:%M',
        'TAG': '//meta[@name="keywords"]/@content',
        'CATEGORY':'//div[@class="breadcrumb"]/ul/li[3]/a/text()',
        'CONTENTS': '//div[@itemprop="articleBody"]/text()',
        'EXCLUDE_TEXT': r'Baca:'
    },
    'WARTAEKONOMI': {
        'NAME': 'Wartaekonomi',
        'START': 'https://www.wartaekonomi.co.id/indeks/%s',
        'ARTICLES': '//div[@class="articleList"]//a/@href',
        'NEXT_PAGES': '//li[@class="page-item active"]/following-sibling::li/a/@href',
        'TITLE': '//h1/text()',
        # 'AUTHOR': '//div[@class="articlePostAuthor mb-4"]/p//span/following-sibling::text()',
        'AUTHOR': '//div[@class="articlePostAuthor mb-4"]/p/span[contains(text(), "Penulis:")]/following-sibling::a/text()',
        'DATE': '//div[@class="articlePostHeader mb-3"]//time/text()',
        'DATE_FORMAT': '%A, %d %B %Y, %H:%M WIB',
        'TAG': '//meta[@name="keywords"]/@content',
        'CATEGORY':'//div[@class="articlePostHeader mb-3"]//ul//a/text()',
        'CONTENTS': '//div[@class="articlePostContent clearfix lh-lg mb-4"]//text()',
        'EXCLUDE_TEXT': r'Baca Juga:'
    },
    'VOI': {
        'NAME': 'Voi',
        'START': 'https://voi.id/artikel/indeks?channel=ALL&tanggal=%s',
        'ARTICLES': '//h3/a/@href',
        'NEXT_PAGES': '//a[@rel="next"]/@href',
        'TITLE': '//strong/text()',
        'AUTHOR': '//div[@class="col-md-10 px-3"]/a//text()',
        'DATE': '//div[@class="single-post-date row mb-3"]//span/text()',
        'DATE_FORMAT': '%d %B %Y,  %H:%M',
        'TAG': '//meta[@name="keywords"]/@content',
        'CATEGORY':'//li[@class="breadcrumb-item active"]//a/text()',
        'CONTENTS': '//div[@class="full-post-body col-8 text-break"]//*/text()',
    },
    'INDOZONE': {
        'NAME': 'Indozone',
        'START': 'https://news.indozone.id/indeks-berita?daterange=',
        'ARTICLES': '//div[@class="latest__item"]/div/a/@href',
        'NEXT_PAGES': '//a[@class="paging__link paging__link--next"]/@href',
        'TITLE': '//h1[@class="read__title"]/text()',
        'AUTHOR': '//meta[@property="dable:author"]/@content',
        'DATE': '//meta[@property="article:published_time"]/@content',
        'DATE_FORMAT': '%Y-%m-%dT%H:%M:%S+07:00',
        'TAG': '//meta[@name="content_Tag"]/@content',
        'CATEGORY':'//ul[@class="breadcrumb__wrap"]/li[2]//text()',
        'CONTENTS': '//article[@class="read__content clearfix"]/p//text()',
        'EXCLUDE_TEXT': r'Baca Juga: '
    },
    'IDNTIMES': {
        'NAME': 'Idntimes',
        'START': 'https://www.idntimes.com/ajax/index?type=all&page=1&date=%s',
        'ARTICLES': '//div[@class="description-latest box-description"]/a/@href',
        'NEXT_PAGES': '//div[@class="text-center infiniteScroll-loading"]/a/@href',
        'TITLE': '//h1[@class="title-text"]/text()',
        # 'AUTHOR': '//div[@class="author-name divide-table-cell"]/a/text()',
        'AUTHOR' : '//meta[@name="author"]/@content',
        'DATE': '//time[@class="date"]/@datetime',
        'DATE_FORMAT': '%d %b %y | %H:%M',
        'TAG': '//div[@class="content-post-topic"]/ul/li/a/text()',
        # 'CATEGORY': '//ol[@class="breadcrumb"]/li/text()',
        'CATEGORY': '//ol[@class="breadcrumb"]/li[2]/text()',
        'CONTENTS': '//article[@id="article-content"]/descendant::text()[not(ancestor::div/@class="editors-pick")]',
        'EXCLUDE_TEXT': r'Baca Juga: '
    },
    'RMOLSUMSEL': {
        'NAME': 'Rmolsumsel',
        'START': 'https://www.rmolsumsel.id/index-berita?filter=%s',
        'ARTICLES': '//h2/a/@href',
        'NEXT_PAGES': '//a[@rel="next"]/@href',
        'TITLE': '//meta[@property="og:title"]/@content',
        'AUTHOR': '//span[@class="author"]/text()',
        'DATE': '//time[@itemprop="datePublished"]/text()',
        'DATE_FORMAT': '%A, %d %B %Y | %H:%M',
        'TAG': '//meta[@name="keywords"]/@content',
        'CATEGORY': '//a[@itemprop="item"]//span/text()',
        'CONTENTS': '//div[@itemprop="text"]//p//text()',
    },
    'GRID': {
        'NAME': 'Grid',
        'START': 'https://www.grid.id/indeks?year=%s&month=%s&day=%s&section_id=',
        'ARTICLES': '//a[@class="news-list__link"]/@href',
        'NEXT_PAGES': '//ul[@class="pagination__number"]//a[@rel="next"]/@href',
        'TITLE': '//meta[@property="og:title"]/@content',
        'AUTHOR': '//meta[@name="content_author"]/@content',
        'DATE': '//meta[@name="content_PublishedDate"]/@content',
        'DATE_FORMAT': '%Y-%m-%d %H:%M:%S',
        'TAG': '//meta[@name="keywords"]/@content',
        'CATEGORY': '//meta[@name="content_category"]/@content',
        'CONTENTS': '//div[@class="read__right read__article read__keyword"]//p//text()',
        'EXCLUDE_TEXT': r'Baca Juga: '
    },
    'KUMPARAN': {
        'NAME': 'Kumparan',
        'START': 'https://kumparan.com/kumparannews',
        # 'ARTICLES': '//div[@data-qa-id="story-result-card"]//div[@class="Viewweb__StyledView-p5eu6e-0 kcaV"]//a[@class="LabelLinkweb-njxxwb-0 cJvuwm"]/@href',
        'ARTICLES': '//div[@data-qa-id="story-result-card"]/div/a/@href',
        # 'NEXT_PAGES': 'https://graphql-v4.kumparan.com/query',
        'NEXT_PAGES': '/',
        'TITLE': '//h1[@data-qa-id="story-title"]/text()',
        'AUTHOR': '//script[@type="application/ld+json"]//text()',
        'DATE': '//script[@type="application/ld+json"]/text()',
        'DATE_FORMAT': '%Y-%m-%dT%H:%M:%S+07:00',
        'TAG': '//span[@data-qa-id="label-tag-topic"]//text()',
        'CATEGORY': '//a[@data-qa-id="channel-name"]//text()',
        'CONTENTS': '//div[@class="components__NormalWidth-sc-l308u-0 jDIEWj"]//text()',
        'EXCLUDE_TEXT': r'ADVERTISEMENT|advertisement|Advertisement',
        'PAYLOAD': {
            "operationName":"FindStoryFeedByPublisherID",
            "variables": {
                "userID":"",
                "publisherID":"1544010202",
                "cursor":"1",
                "cursorType":"PAGE",
                "clientType":"WEB",
                "size":10
            },
            "query":"query FindStoryFeedByPublisherID($publisherID: ID!, $cursor: String!, $cursorType: CursorType!, $size: Int!, $clientType: ClientType) {\n  FindStoryFeedByPublisherID(publisherID: $publisherID, cursor: $cursor, cursorType: $cursorType, size: $size, clientType: $clientType) {\n    edges {\n      ...CompactStory\n      __typename\n    }\n    cursorInfo {\n      ...CursorInfo\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment CompactStory on Story {\n  __typename\n  id\n  authorID\n  title\n  createdAt\n  leadText\n  publishedAt\n  isAgeRestrictedContent\n  slug\n  isStickyStory\n  isShowOnWeb\n  isShowOnApp\n  isDisableComment\n  isDisableLike\n  isSnackable\n  metaDescription\n  readTimeInMinutes\n  storyAddOns {\n    ...StoryAddOn\n    __typename\n  }\n  author {\n    ...SimpleUser\n    __typename\n  }\n  publisher {\n    ...SimplePublisher\n    __typename\n  }\n  leadMedia {\n    ...Media\n    __typename\n  }\n  headline {\n    ...Headline\n    __typename\n  }\n  statistic {\n    ...StoryStatistic\n    __typename\n  }\n  readEligibility\n  productInfo {\n    ...Product\n    __typename\n  }\n  isPrivate\n  collection {\n    ...CompactCollection\n    __typename\n  }\n  internalTags\n}\n\nfragment StoryAddOn on StoryAddOn {\n  object {\n    __typename\n    ... on Polling {\n      ...Polling\n      __typename\n    }\n    ... on Gallery {\n      ...Gallery\n      __typename\n    }\n    ... on KumparanDerma {\n      ...KumparanDerma\n      __typename\n    }\n    ... on Form {\n      ...Form\n      __typename\n    }\n    ... on Recipe {\n      ...Recipe\n      __typename\n    }\n  }\n  addOnType\n  __typename\n}\n\nfragment Polling on Polling {\n  __typename\n  id\n  name\n  description\n  mediaID\n  startsAt\n  endsAt\n  questions {\n    ...Question\n    __typename\n  }\n}\n\nfragment Question on Question {\n  id\n  pollingID\n  detail\n  position\n  choices {\n    ...Choice\n    __typename\n  }\n  __typename\n}\n\nfragment Choice on Choice {\n  id\n  questionID\n  detail\n  mediaID\n  position\n  stats\n  __typename\n}\n\nfragment Gallery on Gallery {\n  name\n  description\n  __typename\n  id\n  createdAt\n  updatedAt\n  galleryMedias {\n    ...GalleryMedia\n    __typename\n  }\n}\n\nfragment GalleryMedia on GalleryMedia {\n  mediaID\n  description\n  caption\n  media {\n    ...Media\n    __typename\n  }\n  __typename\n}\n\nfragment Media on Media {\n  id\n  title\n  description\n  publicID\n  externalURL\n  awsS3Key\n  height\n  width\n  locationName\n  locationLat\n  locationLon\n  mediaType\n  mediaSourceID\n  photographer\n  eventDate\n  internalTags\n  __typename\n}\n\nfragment KumparanDerma on KumparanDerma {\n  id\n  __typename\n}\n\nfragment Form on Form {\n  __typename\n  id\n  title\n  description\n  generateStatus\n  lastGenerated\n  createdBy {\n    ...SimpleUser\n    __typename\n  }\n  createdAt\n  updatedAt\n  endDate\n  pages {\n    ...FormPage\n    __typename\n  }\n  respondent\n  coverMedia {\n    ...Media\n    __typename\n  }\n  accentColor\n  backgroundColor\n  completedResponseTitle\n  completedResponse\n  formResponseConfirmationMail {\n    ...FormResponseConfirmationMail\n    __typename\n  }\n}\n\nfragment FormPage on FormPage {\n  page\n  questions {\n    ...FormQuestion\n    __typename\n  }\n  __typename\n}\n\nfragment FormQuestion on FormQuestion {\n  id\n  formId\n  type\n  description\n  title\n  isRequired\n  createdAt\n  updatedAt\n  addOns {\n    ...QuestionAddOns\n    __typename\n  }\n  __typename\n}\n\nfragment QuestionAddOns on QuestionAddOns {\n  colcount\n  choicesOrder\n  hasOther\n  otherText\n  optionsCaption\n  hasNone\n  hasSelectAll\n  valueTrue\n  valueFalse\n  labelTrue\n  labelFalse\n  rows\n  placeholder\n  choices\n  fileType\n  __typename\n}\n\nfragment SimpleUser on User {\n  __typename\n  id\n  name\n  username\n  aboutMe\n  isVerified\n  profilePictureMedia {\n    ...Media\n    __typename\n  }\n  coverPictureMedia {\n    ...Media\n    __typename\n  }\n  status\n  metaKeyword\n  metaTitle\n  metaDescription\n}\n\nfragment FormResponseConfirmationMail on FormResponseConfirmationMail {\n  title\n  header\n  body\n  hyperlinkURL\n  hyperlinkTitle\n  __typename\n}\n\nfragment Recipe on Recipe {\n  id\n  name\n  description\n  mediaID\n  media {\n    ...Media\n    __typename\n  }\n  portionSize\n  ingredients\n  instructions {\n    step\n    instruction\n    __typename\n  }\n  cookingTime\n  calories\n  createdAt\n  createdBy {\n    ...SimpleUser\n    __typename\n  }\n  updatedAt\n  updatedBy {\n    ...SimpleUser\n    __typename\n  }\n  __typename\n}\n\nfragment Headline on Headline {\n  storyID\n  desktopMedia {\n    ...Media\n    __typename\n  }\n  mobileMedia {\n    ...Media\n    __typename\n  }\n  startTime\n  endTime\n  __typename\n}\n\nfragment StoryStatistic on StoryStatistic {\n  storyID\n  commentCount\n  likeCount\n  __typename\n}\n\nfragment SimplePublisher on Publisher {\n  __typename\n  id\n  name\n  slug\n  description\n  isVerified\n  isPremium\n  avatarMedia {\n    ...Media\n    __typename\n  }\n  instagramURL\n  twitterURL\n  facebookURL\n  website\n  isCorporateSubscriber\n}\n\nfragment Product on Product {\n  id\n  sku\n  objectID\n  objectType\n  object {\n    ... on Story {\n      id\n      slug\n      title\n      leadText\n      author {\n        id\n        username\n        __typename\n      }\n      publisher {\n        id\n        slug\n        __typename\n      }\n      leadMedia {\n        id\n        externalURL\n        __typename\n      }\n      __typename\n    }\n    ... on Collection {\n      id\n      slug\n      title\n      description\n      coverMedia {\n        id\n        externalURL\n        __typename\n      }\n      __typename\n    }\n    ... on SubscriptionPackage {\n      ...SimpleSubscriptionPackage\n      __typename\n    }\n    __typename\n  }\n  normalPrice {\n    ...Money\n    __typename\n  }\n  price {\n    ...Money\n    __typename\n  }\n  taxCategory {\n    ...TaxCategory\n    __typename\n  }\n  __typename\n}\n\nfragment TaxCategory on TaxCategory {\n  id\n  name\n  rateInPercentage\n  isInclusive\n  __typename\n}\n\nfragment Money on Money {\n  currencyCode\n  units\n  cents\n  __typename\n}\n\nfragment SimpleSubscriptionPackage on SubscriptionPackage {\n  id\n  name\n  subscriptionDescription: description\n  isActive\n  isRecurring\n  period\n  periodType\n  gracePeriodInSeconds\n  __typename\n}\n\nfragment CompactCollection on Collection {\n  __typename\n  id\n  title\n  isPinned\n  slug\n  createdAt\n  readEligibility\n  updatedAt\n  lastStoryAddedAt\n  description\n  coverMedia {\n    ...Media\n    __typename\n  }\n  readEligibility\n  productInfo {\n    ...Product\n    __typename\n  }\n  storiesCount\n  videoDescriptionLink\n  premiumInfo {\n    setPremiumAt\n    __typename\n  }\n  kumparanPlusInfo {\n    createdAt\n    __typename\n  }\n  topics {\n    ...Topic\n    __typename\n  }\n}\n\nfragment Topic on Topic {\n  __typename\n  id\n  name\n  slug\n  description\n  coverMedia {\n    ...Media\n    __typename\n  }\n  metaName\n  metaKeywordsV2\n  metaDescription\n}\n\nfragment CursorInfo on CursorInfo {\n  size\n  count\n  countPage\n  hasMore\n  cursor\n  cursorType\n  nextCursor\n  __typename\n}\n"
        }
    },
    'JAWAPOS': {
        'NAME': 'Jawapos',
        'START': 'https://www.jawapos.com/berita-hari-ini/?date=%s',
        'NEXT_PAGES': 'https://www.jawapos.com/desktop-get-posts/',
        'ARTICLES': '//h3[@class="post-list__title"]//a/@href',
        'TITLE': '//title/text()',
        'AUTHOR': '//meta[@name="author"]/@content',
        'DATE': '//meta[@property="article:published_time"]/@content',
        'DATE_FORMAT': '%Y-%m-%d %H:%M:%S',
        'TAG': '//div[@class="tag-list"]//text()[not(ancestor::aside[@class="main-sidebar"])]',
        'CATEGORY': '//div[@class="category"]//text()',
        'CONTENTS': '//div[@class="content"]//text()',
        'FORM_DATA': {
            'section': 'search',
            'post_type%5B0%5D': 'post',
            'post_type%5B1%5D': 'photo',
            'post_type%5B2%5D': 'video',
            'post_type%5B3%5D': 'radar',
            'per_page': '15',
            'terms': 'all',
            'date': '',
            'security': '4d6482604c',
            'page_no': '2'
        }
    },
    'TRIBUNACEH': {
        'NAME': 'Tribun Aceh',
        'START': 'https://aceh.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIB',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article multi-fontsize"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNSUMSEL': {
        'NAME': 'Tribun Sumsel',
        'START': 'https://sumsel.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIB',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNPEKANBARU': {
        'NAME': 'Tribun Pekanbaru',
        'START': 'https://pekanbaru.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIB',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNJAMBI': {
        'NAME': 'Tribun Jambi',
        'START': 'https://jambi.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIB',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNLAMPUNG': {
        'NAME': 'Tribun Lampung',
        'START': 'https://lampung.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIB',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNBANGKA': {
        'NAME': 'Tribun Bangka',
        'START': 'https://bangka.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIB',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNPONTIANAK': {
        'NAME': 'Tribun Pontianak',
        'START': 'https://pontianak.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIB',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNKALTIM': {
        'NAME': 'Tribun Kaltim',
        'START': 'https://kaltim.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WITA',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNBANJARMASIN': {
        'NAME': 'Tribun Banjarmasin',
        'START': 'https://banjarmasin.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WITA',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNKALTARA': {
        'NAME': 'Tribun Kaltara',
        'START': 'https://kaltara.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WITA',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNBATAM': {
        'NAME': 'Tribun Batam',
        'START': 'https://batam.tribunnews.com/index-news/kepri?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIB',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNAMBON': {
        'NAME': 'Tribun Ambon',
        'START': 'https://ambon.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIT',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNBALI': {
        'NAME': 'Tribun Bali',
        'START': 'https://bali.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WITA',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNBANTEN': {
        'NAME': 'Tribun Banten',
        'START': 'https://banten.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIB',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNJABAR': {
        'NAME': 'Tribun Jabar',
        'START': 'https://jabar.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIB',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNJATENG': {
        'NAME': 'Tribun Jateng',
        'START': 'https://jateng.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIB',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNJATIM': {
        'NAME': 'Tribun Jatim',
        'START': 'https://jatim.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIB',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNKUPANG': {
        'NAME': 'Tribun Kupang',
        'START': 'https://kupang.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WITA',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNMAKASSAR': {
        'NAME': 'Tribun Makassar',
        'START': 'https://makassar.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WITA',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNMANADO': {
        'NAME': 'Tribun Manado',
        'START': 'https://manado.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WITA',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNPALU': {
        'NAME': 'Tribun Palu',
        'START': 'https://palu.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WITA',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNPAPUA': {
        'NAME': 'Tribun Papua',
        'START': 'https://papua.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIT',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNTERNATE': {
        'NAME': 'Tribun Ternate',
        'START': 'https://ternate.tribunnews.com/index-news/maluku-utara?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIT',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNBENGKULU': {
        'NAME': 'Tribun Bengkulu',
        'START': 'https://bengkulu.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIB',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNPADANG': {
        'NAME': 'Tribun Padang',
        'START': 'https://padang.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIB',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNMEDAN': {
        'NAME': 'Tribun Medan',
        'START': 'https://medan.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIB',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNJAKARTA': {
        'NAME': 'Tribun Jakarta',
        'START': 'https://jakarta.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIB',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNLOMBOK': {
        'NAME': 'Tribun Lombok',
        'START': 'https://lombok.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WITA',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNKALTENG': {
        'NAME': 'Tribun Kalteng',
        'START': 'https://kalteng.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIB',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize editcontent"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNGORONTALO': {
        'NAME': 'Tribun Gorontalo',
        'START': 'https://gorontalo.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WITA',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNSULBAR': {
        'NAME': 'Tribun Sulbar',
        'START': 'https://sulbar.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WITA',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNSULTRA': {
        'NAME': 'Tribun Sultra',
        'START': 'https://sultra.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WITA',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNPAPUABARAT': {
        'NAME': 'Tribun Papua Barat',
        'START': 'https://papuabarat.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIT',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'TRIBUNSORONG': {
        'NAME': 'Tribun Sorong',
        'START': 'https://sorong.tribunnews.com/index-news?date=%s',
        'ARTICLES': '//h3[@class="f16 fbo"]/a/@href',
        'NEXT_PAGES': '//div[@class="paging"]//a[text()="Next"]/@href',
        'TITLE': '//h1[@id="arttitle"]/text()',
        'AUTHOR': '//div[@class="credit"]//a/text()',
        'DATE': '//time/span/text()',
        'DATE_FORMAT': '%A, %d %B %Y %H:%M WIT',
        'TAG': '//h5[@class="tagcload3 tagcloud3"]//text()',
        'CATEGORY': '//li[@itemprop="itemListElement"][2]//span/text()',
        'CONTENTS': '//div[@class="side-article txt-article multi-fontsize"]//p//text()',
        'EXCLUDE_LINK': '//div[@class="side-article txt-article"]/script/text() | //p[@class="baca"]//text()',
        'ART_DATE': '//li[@class="ptb15"]/time/text()'
    },
    'USER_AGENT': "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0",
    'ALLOWED_DOMAIN': [
        'www.tribunnews.com',
        'news.detik.com',
        'kompas.com',
        'tempo.co',
        'www.cnnindonesia.com',
        'republika.co.id',
        'sindonews.com',
        'liputan6.com',
        'www.beritasatu.com',
        'bisnis.com',
        'mediaindonesia.com',
        'antaranews.com',
        'okezone.com',
        'viva.co.id',
        'pikiran-rakyat.com',
        'www.thejakartapost.com',
        'metrotvnews.com',
        'www.suaramerdeka.com',
        'kontan.co.id',
        'inilah.com',
        'www.merdeka.com',
        'www.suara.com',
        'www.beritajakarta.id',
        'www.cnbcindonesia.com',
        'www.kumparan.com',
        'graphql-v4.kumparan.com',
        'www.ihram.co.id',
        'jawapos.com',
        'www.metrojambi.com',
        'inews.id',
        'jpnn.com',
        'medcom.id',
        'wartaekonomi.co.id',
        'voi.id',
        'indozone.id',
        'idntimes.com',
        'rmolsumsel.id',
        'grid.id',
        'aceh.tribunnews.com',
        'sumsel.tribunnews.com',
        'pekanbaru.tribunnews.com',
        'tribun.tribunnews.com',
        'jambi.tribunnews.com',
        'lampung.tribunnews.com',
        'bangka.tribunnews.com',
        'pontianak.tribunnews.com',
        'kaltim.tribunnews.com',
        'banjarmasin.tribunnews.com',
        'kaltara.tribunnews.com',
        'batam.tribunnews.com',
        'ambon.tribunnews.com',
        'bali.tribunnews.com',
        'banten.tribunnews.com',
        'jabar.tribunnews.com',
        'jateng.tribunnews.com',
        'jatim.tribunnews.com',
        'kupang.tribunnews.com',
        'makassar.tribunnews.com',
        'manado.tribunnews.com',
        'palu.tribunnews.com',
        'papua.tribunnews.com',
        'ternate.tribunnews.com',
        'bengkulu.tribunnews.com',
        'padang.tribunnews.com',
        'medan.tribunnews.com',
        'jakarta.tribunnews.com',
        'lombok.tribunnews.com',
        'kalteng.tribunnews.com',
        'gorontalo.tribunnews.com',
        'sulbar.tribunnews.com',
        'sultra.tribunnews.com',
        'papuabarat.tribunnews.com',
        'sorong.tribunnews.com',
    ],
    'TRIBUN_2' : [
        "Tribun Aceh", 
        "Tribun Sumsel", 
        "Tribun Pekanbaru", 
        "Tribun Jambi",
        "Tribun Lampung",
        "Tribun Bangka",
        "Tribun Pontianak",
        "Tribun Kaltim",
        "Tribun Banjarmasin",
        "Tribun Kaltara",
        "Tribun Batam",
        "Tribun Ambon",
        "Tribun Bali",
        "Tribun Banten",
        "Tribun Jabar",
        "Tribun Jateng",
        "Tribun Jatim",
        "Tribun Kupang",
        "Tribun Makassar",
        "Tribun Manado",
        "Tribun Palu",
        "Tribun Papua",
        "Tribun Ternate",
        "Tribun Bengkulu",
        "Tribun Padang",
        "Tribun Medan",
        "Tribun Jakarta",
        "Tribun Lombok",
        "Tribun Kalteng",
        "Tribun Gorontalo",
        "Tribun Sulbar",
        "Tribun Sultra",
        "Tribun Papua Barat",
        "Tribun Sorong",
    ]
}


# CONFIG = {
#     'DETIK': {
#         'NAME': 'None',
#         'START': 'Lorem Ipsum',
#         'ARTICLES': 'Lorem Ipsum',
#         'NEXT_PAGES': 'Lorem Ipsum',
#         'TITLE': 'Lorem Ipsum',
#         'AUTHOR': 'Lorem Ipsum',
#         'DATE': 'Lorem Ipsum',
#         'TAG': 'Lorem Ipsum',
#         'CATEGORY': 'Lorem Ipsum',
#         'CONTENTS': 'Lorem Ipsum',
#         'EXCLUDE_LINK': 'Lorem Ipsum',
#         'EXCLUDE_TEXT': r'Lorem Ipsum',
#         'STOP_CRITERION': r'Lorem Ipsum'
#     },
# }
